export const NAVBARITEMS = [
  {
    label: "Home",
    to: "/",
  },
  {
    label: "Find a Doctor",
    to: "/findDoctor",
  },
  // {
  //   label: "Services",
  //   to: "/services",
  // },
  // {
  //   label: "About Us",
  //   to: "/aboutus",
  // },
  {
    label: "Contact us",
    to: "/contactus",
  },
  {
    label: "Doctor's Login",
    to: "/signin",
  },
];

export const NAVBARDOCTORITEMS = [
  {
    label: "Appointments",
    to: "/appointments",
  },
  {
    label: "Schedules",
    to: "/schedules",
  },
];

export const HOME_HERO_SECTION = {
  newUpdate: "Get the latest update of Coronavirus (Covid-19)",
  headline: "Book appointment with any doctor near you!",
  subText:
    "Select your doctor and preferred time slot according to your convenience and availability.",
};

import SearchDoctor from "@assets/images/searchDoctor.svg";
import Appointment from "@assets/images/sheduleAppointment.svg";
import Support from "@assets/images/support.svg";

export const HOME_SERVICE_SECTION = {
  subTitle: "Services",
  title: "3 Easy Steps and Get Your Solution",
  description:
    "All SMART CARE services are available in web and mobile app versions with fast service responses, and support from experienced doctors and specialists throughout India.",
  services: [
    {
      id: 1,
      title: "Search Doctors",
      image: SearchDoctor,
      link: "/findDoctor",
    },
    {
      id: 2,
      title: "Schedule Appointment",
      image: Appointment,
    },
    {
      id: 3,
      title: "24/7 Support",
      image: Support,
    },
  ],
};

import InternalMedicine from "@assets/images/icon-internal-medicine.png";
import GeneralSurgery from "@assets/images/icon-general-surgery.png";
import Pediatrics from "@assets/images/icon-pediatrics.png";
import ObstetricsGynecology from "@assets/images/icon-obstetrics-gynecology.png";
import OrthopedicSurgeons from "@assets/images/icon-orthopedic-surgeons.png";

import Opthalmologist from "@assets/images/icon-ophthalmologist.png";
import Gastroenterology from "@assets/images/icon-gastroenterology.png";
import Urologist from "@assets/images/icon-urologist.png";
import Dermatologist from "@assets/images/icon-dermatologist.png";
import Neurologist from "@assets/images/icon-neurologist.png";

import DoctorImage from "@assets/images/HomeHeroImage.jpg";

export const FIND_DOCTORS_DATA = [
  {
    state: "Gujarat",
    city: "Bhavnagar",
    specialist: [
      {
        icon: InternalMedicine,
        name: "Internal medicine",
        id: 1,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Bhavnagar",
            location: "Vijayrajnagar, Bhavnagar",
            hospital: "Civil Hospital",
            fee: 200,
            image: DoctorImage,
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            hospital: "Civil Hospital",

            image: DoctorImage,
          },
        ],
      },
      {
        icon: GeneralSurgery,
        name: "General Surgery",
        id: 2,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Bhavnagar",
            location: "Vijayrajnagar, Bhavnagar",
            hospital: "Civil Hospital",
            fee: 200,
            image: DoctorImage,
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            hospital: "Civil Hospital",

            image: DoctorImage,
          },
        ],
      },
      {
        icon: Pediatrics,
        name: "Pediatrics",
        id: 3,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Bhavnagar",
            location: "Vijayrajnagar, Bhavnagar",
            hospital: "Civil Hospital",
            fee: 200,
            image: DoctorImage,
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            hospital: "Civil Hospital",

            image: DoctorImage,
          },
        ],
      },
      {
        icon: ObstetricsGynecology,
        name: "Obstetrics & Gynecology",
        id: 4,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Bhavnagar",
            location: "Vijayrajnagar, Bhavnagar",
            hospital: "Civil Hospital",
            fee: 200,
            image: DoctorImage,
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            hospital: "Civil Hospital",
            image: DoctorImage,
          },
        ],
      },
      {
        icon: OrthopedicSurgeons,
        name: "Orthopedic Surgeons",
        id: 5,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Bhavnagar",
            location: "Vijayrajnagar, Bhavnagar",
            hospital: "Civil Hospital",
            fee: 200,
            image: DoctorImage,
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            hospital: "Civil Hospital",
            image: DoctorImage,
          },
        ],
      },
    ],
  },
  {
    state: "Gujarat",
    city: "Anand",
    specialist: [
      {
        icon: InternalMedicine,
        name: "Internal medicine",
        id: 6,
        doctors: [],
      },
      {
        icon: GeneralSurgery,
        name: "General Surgery",
        id: 7,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Pediatrics,
        name: "Pediatrics",
        id: 8,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: ObstetricsGynecology,
        name: "Obstetrics & Gynecology",
        id: 9,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: OrthopedicSurgeons,
        name: "Orthopedic Surgeons",
        id: 36,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Opthalmologist,
        name: "Opthalmologist",
        id: 37,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Gastroenterology,
        name: "Gastroenterology",
        id: 38,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Urologist,
        name: "Urologist",
        id: 39,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Dermatologist,
        name: "Dermatologist",
        id: 40,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Neurologist,
        name: "Neurologist / Neurosurgeon",
        id: 41,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
    ],
  },
  {
    state: "Gujarat",
    city: "Jaipur",
    specialist: [
      {
        icon: InternalMedicine,
        name: "Internal medicine",
        id: 11,
        doctors: [],
      },
      {
        icon: GeneralSurgery,
        name: "General Surgery",
        id: 12,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Pediatrics,
        name: "Pediatrics",
        id: 13,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: ObstetricsGynecology,
        name: "Obstetrics & Gynecology",
        id: 14,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: OrthopedicSurgeons,
        name: "Orthopedic Surgeons",
        id: 15,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
    ],
  },
  {
    state: "Gujarat",
    city: "Jodhpur",
    specialist: [
      {
        icon: InternalMedicine,
        name: "Internal medicine",
        id: 16,
        doctors: [],
      },
      {
        icon: GeneralSurgery,
        name: "General Surgery",
        id: 17,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Pediatrics,
        name: "Pediatrics",
        id: 18,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: ObstetricsGynecology,
        name: "Obstetrics & Gynecology",
        id: 19,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: OrthopedicSurgeons,
        name: "Orthopedic Surgeons",
        id: 20,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            icon: Opthalmologist,
            name: "Opthalmologist",
            id: 42,
            doctors: [
              {
                name: "Dr. S. A. Chauhan",
                specialty: "Dentist",
                experience: 24,
                locationCity: "Anand",
                location: "Vijayrajnagar, Bhavnagar",
                fee: 200,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
              {
                name: "Dr. Parth Iyer",
                specialty: "Dentist",
                experience: 12,
                locationCity: "Anand",
                location: "Bhavnagar, Bhavnagar",
                fee: 150,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
            ],
          },
          {
            icon: Gastroenterology,
            name: "Gastroenterology",
            id: 43,
            doctors: [
              {
                name: "Dr. S. A. Chauhan",
                specialty: "Dentist",
                experience: 24,
                locationCity: "Anand",
                location: "Vijayrajnagar, Bhavnagar",
                fee: 200,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
              {
                name: "Dr. Parth Iyer",
                specialty: "Dentist",
                experience: 12,
                locationCity: "Anand",
                location: "Bhavnagar, Bhavnagar",
                fee: 150,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
            ],
          },
          {
            icon: Urologist,
            name: "Urologist",
            id: 44,
            doctors: [
              {
                name: "Dr. S. A. Chauhan",
                specialty: "Dentist",
                experience: 24,
                locationCity: "Anand",
                location: "Vijayrajnagar, Bhavnagar",
                fee: 200,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
              {
                name: "Dr. Parth Iyer",
                specialty: "Dentist",
                experience: 12,
                locationCity: "Anand",
                location: "Bhavnagar, Bhavnagar",
                fee: 150,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
            ],
          },
          {
            icon: Dermatologist,
            name: "Dermatologist",
            id: 45,
            doctors: [
              {
                name: "Dr. S. A. Chauhan",
                specialty: "Dentist",
                experience: 24,
                locationCity: "Anand",
                location: "Vijayrajnagar, Bhavnagar",
                fee: 200,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
              {
                name: "Dr. Parth Iyer",
                specialty: "Dentist",
                experience: 12,
                locationCity: "Anand",
                location: "Bhavnagar, Bhavnagar",
                fee: 150,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
            ],
          },
          {
            icon: Neurologist,
            name: "Neurologist / Neurosurgeon",
            id: 46,
            doctors: [
              {
                name: "Dr. S. A. Chauhan",
                specialty: "Dentist",
                experience: 24,
                locationCity: "Anand",
                location: "Vijayrajnagar, Bhavnagar",
                fee: 200,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
              {
                name: "Dr. Parth Iyer",
                specialty: "Dentist",
                experience: 12,
                locationCity: "Anand",
                location: "Bhavnagar, Bhavnagar",
                fee: 150,
                image: DoctorImage,
                hospital: "Civil Hospital",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    state: "Gujarat",
    city: "Udaipur",
    specialist: [
      {
        icon: InternalMedicine,
        name: "Internal medicine",
        id: 21,
        doctors: [],
      },
      {
        icon: GeneralSurgery,
        name: "General Surgery",
        id: 22,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Pediatrics,
        name: "Pediatrics",
        id: 23,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: ObstetricsGynecology,
        name: "Obstetrics & Gynecology",
        id: 24,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: OrthopedicSurgeons,
        name: "Orthopedic Surgeons",
        id: 25,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
    ],
  },
  {
    state: "Karnataka",
    city: "Bagalkote",
    specialist: [
      {
        icon: InternalMedicine,
        name: "Internal medicine",
        id: 26,
        doctors: [],
      },
      {
        icon: GeneralSurgery,
        name: "General Surgery",
        id: 27,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Pediatrics,
        name: "Pediatrics",
        id: 28,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: ObstetricsGynecology,
        name: "Obstetrics & Gynecology",
        id: 29,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: OrthopedicSurgeons,
        name: "Orthopedic Surgeons",
        id: 30,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
    ],
  },
  {
    state: "Karnataka",
    city: "Bengaluru",
    specialist: [
      {
        icon: InternalMedicine,
        name: "Internal medicine",
        id: 31,
        doctors: [],
      },
      {
        icon: GeneralSurgery,
        name: "General Surgery",
        id: 32,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Pediatrics,
        name: "Pediatrics",
        id: 33,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: ObstetricsGynecology,
        name: "Obstetrics & Gynecology",
        id: 34,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: OrthopedicSurgeons,
        name: "Orthopedic Surgeons",
        id: 35,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Opthalmologist,
        name: "Opthalmologist",
        id: 47,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Gastroenterology,
        name: "Gastroenterology",
        id: 48,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Urologist,
        name: "Urologist",
        id: 49,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Dermatologist,
        name: "Dermatologist",
        id: 50,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
      {
        icon: Neurologist,
        name: "Neurologist / Neurosurgeon",
        id: 51,
        doctors: [
          {
            name: "Dr. S. A. Chauhan",
            specialty: "Dentist",
            experience: 24,
            locationCity: "Anand",
            location: "Vijayrajnagar, Bhavnagar",
            fee: 200,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
          {
            name: "Dr. Parth Iyer",
            specialty: "Dentist",
            experience: 12,
            locationCity: "Anand",
            location: "Bhavnagar, Bhavnagar",
            fee: 150,
            image: DoctorImage,
            hospital: "Civil Hospital",
          },
        ],
      },
    ],
  },
];

import IconMail from "@assets/icons/icon-mail.svg";
import IconCall from "@assets/icons/icon-call.svg";
import IconWebsite from "@assets/icons/icon-website.png";
import IconWhatsapp from "@assets/icons/icon-whatsapp.svg";
import IconLocation from "@assets/icons/icon-location.svg";

export const CONTACT_US_DATA = {
  title: "Contact Us",
  subTitle:
    "We welcome your inquiries and are here to assist you. Please use the following details to get in touch with us.",
  website: {
    icon: IconWebsite,
    website: "https://karmatimefoundation.org",
    text: "Visit our official website or follow us on social media for the latest updates and initiatives:",
    title: "Connect With Us",
  },
  whatsapp: {
    icon: IconWhatsapp,
    website: "https://karmatimefoundation.org",
  },
  contactForm: {
    title: "We look forward to hearing from you!",
    text: "",
  },
  Contacts: [
    {
      icon: IconMail,
      data: ["myhealth.app0912@gmail.com"],
    },
    {
      icon: IconLocation,
      data: ["Banglore, Karnataka, India"],
    },
    {
      icon: IconCall,
      data: ["+91 77956 09690"],
    },
  ],
};

export const APP_DATA = {
  title: "Download app and  make appointment with your doctor.",
  playStoreLink:
    "https://play.google.com/store/apps/details?id=com.chirasumyhealth.patient",
  appleStoreLink:
    "https://apps.apple.com/in/app/chirasu-my-health/id6747678527",
};

export const generatePasswordFromUser = (formData) => {
  const { firstName, lastName, phone } = formData;

  const phoneStr = phone.toString();
  const last4 = phoneStr.slice(-4);

  let namePart = firstName;
  if (firstName.length < 2) {
    namePart = firstName + lastName;
  }

  return `${namePart}$$${last4}`;
};
